syntax = "proto3";
package protocol.ssmsg;
import "loginsvr/SSLoginMsg.proto";
import "chatsvr/SSChatMsg.proto";
enum SSMsgType{
    EN_UNKOWN = 0;
    EN_HEARTBEAT = 1;
    EN_LOGIN = 2;
    EN_CHAT = 3;
    EN_WHISPER = 4;
}

message SSMsgReq{
    SSMsgType msgType = 1;
    oneof body{
        protocol.ssloginmsg.SSLoginMsgReq loginReq = 2;
        protocol.sschatmsg.SSChatMsgReq chatReq = 3;
    }
}

message SSMsgRsp{
    SSMsgType msgType = 1;
    oneof body{
        protocol.ssloginmsg.SSLoginMsgRsp loginRsp = 2;
        protocol.sschatmsg.SSChatMsgRsp chatRsp = 3;
    }
}