apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatesvr
  namespace: game-im-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatesvr
  template:
    metadata:
      labels:
        app: gatesvr
    spec:
      containers:
      - name: gatesvr
        image: game-im/gatesvr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        envFrom:
        - configMapRef:
            name: game-im-config
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}